import { db } from './db';
import { users, bibleVerses, habits, quarterlyPlans } from './schema';
import { randomUUID } from 'crypto';
import { scryptSync } from 'crypto';

// Función oficial de encriptación para la contraseña del Administrador
function hashPassword(password: string): string {
  const salt = 'journaling-integral-salt-key';
  return scryptSync(password, salt, 64).toString('hex');
}

async function seed() {
  console.log('Iniciando carga de datos...');

  try {
    await db.delete(bibleVerses);
    console.log('Librería de versículos restablecida.');
  } catch (e) {
    console.log('Limpieza previa de versículos omitida.');
  }

  const verses = [
    // TÓPICO: FINANZAS Y MAYORDOMÍA (30 Versículos)
    {
      id: randomUUID(),
      reference: 'Proverbios 21:5',
      text: 'Los pensamientos del diligente ciertamente tienden a la abundancia; mas todo el que se apresura alocadamente, de cierto va a la pobreza.',
      interpretation: 'Planificación sobre impulso. Controlar los egresos y diseñar presupuestos semanales es obediencia y sabiduría.',
      recommendedLevel: 1,
      topic: 'Finanzas',
    },
    {
      id: randomUUID(),
      reference: 'Proverbios 22:7',
      text: 'El rico se enseñorea de los pobres, y el que toma prestado es siervo del que presta.',
      interpretation: 'La deuda limita tu libertad y tu capacidad de dejar un legado. Diseña un plan de salida inmediato.',
      recommendedLevel: 2,
      topic: 'Finanzas',
    },
    {
      id: randomUUID(),
      reference: 'Lucas 16:11',
      text: 'Pues si en las riquezas injustas no fuisteis fieles, ¿quién os confiará lo verdadero?',
      interpretation: 'La buena administración de los recursos terrenales determina tu preparación para recibir asignaciones mayores.',
      recommendedLevel: 1,
      topic: 'Finanzas',
    },
    {
      id: randomUUID(),
      reference: 'Proverbios 3:9-10',
      text: 'Honra a Jehová con tus bienes, y con las primicias de todos tus frutos; y serán llenos tus graneros con abundancia.',
      interpretation: 'Poner a Dios primero en tus ingresos redefine la soberanía de tus finanzas y rompe la mentalidad de escasez.',
      recommendedLevel: 1,
      topic: 'Finanzas',
    },
    {
      id: randomUUID(),
      reference: '1 Timoteo 6:10',
      text: 'Porque raíz de todos los males es el amor al dinero, el cual codiciando algunos, se extraviaron de la fe.',
      interpretation: 'El dinero es un sirviente excelente pero un maestro tirano. Administra con enfoque en servicio, no en codicia.',
      recommendedLevel: 2,
      topic: 'Finanzas',
    },
    {
      id: randomUUID(),
      reference: 'Hebreos 13:5',
      text: 'Sean vuestras costumbres sin avaricia, contentos con lo que tenéis ahora; porque el dijo: No te desampararé, ni te dejaré.',
      interpretation: 'El contentamiento rompe el ciclo del consumo reactivo que destruye el flujo de caja de tu negocio.',
      recommendedLevel: 2,
      topic: 'Finanzas',
    },
    {
      id: randomUUID(),
      reference: 'Proverbios 22:9',
      text: 'El ojo misericordioso será bendito, porque dio de su pan al indigente.',
      interpretation: 'La generosidad activa es el mejor antídoto contra el temor a la escasez. Siembra en otros hoy.',
      recommendedLevel: 1,
      topic: 'Finanzas',
    },
    {
      id: randomUUID(),
      reference: 'Proverbios 28:20',
      text: 'El hombre de verdad tendrá muchas bendiciones; mas el que se apresura a enriquecerse no será sin culpa.',
      interpretation: 'Huye del enriquecimiento fácil o sin esfuerzo. El valor sólido toma tiempo y constancia en construirse.',
      recommendedLevel: 2,
      topic: 'Finanzas',
    },
    {
      id: randomUUID(),
      reference: 'Deuteronomio 8:18',
      text: 'Sino acuérdate de Jehová tu Dios, porque él te da el poder para hacer las riquezas, a fin de confirmar su pacto.',
      interpretation: 'Tus talentos empresariales provienen de tu creador. Tu éxito comercial es para bendecir a tu oikos.',
      recommendedLevel: 2,
      topic: 'Finanzas',
    },
    {
      id: randomUUID(),
      reference: 'Eclesiastés 5:10',
      text: 'El que ama el dinero, no se saciará de dinero; y el que ama el mucho tener, no sacará fruto.',
      interpretation: 'La acumulación vacía no genera paz mental. Busca impacto y legado, no solo números en una cuenta bancaria.',
      recommendedLevel: 3,
      topic: 'Finanzas',
    },
    {
      id: randomUUID(),
      reference: 'Proverbios 13:11',
      text: 'Las riquezas de vanidad disminuirán; pero el que recoge con mano laboriosa las aumenta.',
      interpretation: 'La micro-acción constante multiplica los activos. Valora los pequeños incrementos consistentes.',
      recommendedLevel: 1,
      topic: 'Finanzas',
    },
    {
      id: randomUUID(),
      reference: 'Romanos 13:8',
      text: 'No debáis a nadie nada, sino el amaros unos a otros; porque el que ama al prójimo, ha cumplido la ley.',
      interpretation: 'La libertad financiera acelera tu capacidad de bendecir. No asumas deudas de consumo innecesarias.',
      recommendedLevel: 2,
      topic: 'Finanzas',
    },
    {
      id: randomUUID(),
      reference: 'Proverbios 11:24',
      text: 'Hay quienes reparten, y les es añadido más; y hay quienes retienen más de lo que es justo, pero vienen a la pobreza.',
      interpretation: 'La paradoja del reino: el acaparamiento paraliza los recursos, mientras que la mayordomía generosa abre puertas.',
      recommendedLevel: 2,
      topic: 'Finanzas',
    },
    {
      id: randomUUID(),
      reference: 'Proverbios 11:25',
      text: 'El alma generosa será prosperada; y el que saciare, él también será saciado.',
      interpretation: 'Invierte en las personas. Servir con excelencia es la semilla de la rentabilidad sostenible.',
      recommendedLevel: 1,
      topic: 'Finanzas',
    },
    {
      id: randomUUID(),
      reference: 'Proverbios 28:19',
      text: 'El que labra su tierra se saciará de pan; mas el que sigue a los ociosos se llenará de pobreza.',
      interpretation: 'Foco en la producción. Labra tu propio modelo de negocio antes de buscar diversificar sin dirección.',
      recommendedLevel: 1,
      topic: 'Finanzas',
    },
    {
      id: randomUUID(),
      reference: 'Mateo 6:24',
      text: 'Ninguno puede servir a dos señores; porque o aborrecerá al uno y amará al otro... No podéis servir a Dios y a las riquezas.',
      interpretation: 'El dinero debe ser tu herramienta de servicio, jamás tu objeto de adoración o motor de identidad.',
      recommendedLevel: 3,
      topic: 'Finanzas',
    },
    {
      id: randomUUID(),
      reference: 'Salmos 37:21',
      text: 'El impío toma prestado, y no paga; mas el justo tiene misericordia, y da.',
      interpretation: 'Cumplir tus compromisos crediticios y de pago es el termómetro de tu integridad y credibilidad comercial.',
      recommendedLevel: 2,
      topic: 'Finanzas',
    },
    {
      id: randomUUID(),
      reference: 'Proverbios 10:22',
      text: 'La bendición de Jehová es la que enriquece, y no añade tristeza con ella.',
      interpretation: 'El éxito que destruye tu salud o tu familia no es bendición real. Busca el progreso integral y en paz.',
      recommendedLevel: 2,
      topic: 'Finanzas',
    },
    {
      id: randomUUID(),
      reference: 'Proverbios 13:22',
      text: 'El bueno dejará herederos a los hijos de sus hijos; pero la riqueza del pecador está guardada para el justo.',
      interpretation: 'Mentalidad de legado. No planifiques para un trimestre; planifica para construir un patrimonio generacional.',
      recommendedLevel: 3,
      topic: 'Finanzas',
    },
    {
      id: randomUUID(),
      reference: 'Proverbios 19:17',
      text: 'A Jehová presta el que da al pobre, y el bien que ha hecho, se lo volverá a pagar.',
      interpretation: 'Tus presupuestos deben destinar un porcentaje fijo para la obra social y el socorro de tu comunidad.',
      recommendedLevel: 1,
      topic: 'Finanzas',
    },
    {
      id: randomUUID(),
      reference: 'Proverbios 21:20',
      text: 'Tesoro precioso y aceite hay en la casa del sabio; mas el hombre insensato todo lo disipa.',
      interpretation: 'La disciplina del ahorro. Conservar provisiones te prepara para las oportunidades de inversión del mañana.',
      recommendedLevel: 2,
      topic: 'Finanzas',
    },
    {
      id: randomUUID(),
      reference: 'Hageo 2:8',
      text: 'Mía es la plata, y mío es el oro, dice Jehová de los ejércitos.',
      interpretation: 'Abandona el estrés del control absoluto. Eres el mayordomo administrador, no el dueño del universo.',
      recommendedLevel: 1,
      topic: 'Finanzas',
    },
    {
      id: randomUUID(),
      reference: 'Malatías 3:10',
      text: 'Traed todos los diezmos al alfolí y haya alimento en mi casa; y probadme ahora en esto...',
      interpretation: 'La generosidad sistemática abre ventanas de discernimiento y rompe las ataduras de la avaricia personal.',
      recommendedLevel: 2,
      topic: 'Finanzas',
    },
    {
      id: randomUUID(),
      reference: 'Filipenses 4:19',
      text: 'Mi Dios, pues, suplirá todo lo que os falte conforme a sus riquezas en gloria en Cristo Jesús.',
      interpretation: 'Sustento garantizado. Tu enfoque debe estar en gobernar bien tu mente hoy, Dios se ocupa de la provisión.',
      recommendedLevel: 1,
      topic: 'Finanzas',
    },
    {
      id: randomUUID(),
      reference: 'Proverbios 22:26-27',
      text: 'No estés entre los que se obligan, ni entre los que salen por fiadores de deudas; porque si no tuvieres para pagar, ¿por qué han de quitar tu cama?',
      interpretation: 'Evita respaldar obligaciones ajenas que pongan en riesgo la paz financiera y el sustento de tu hogar.',
      recommendedLevel: 2,
      topic: 'Finanzas',
    },
    {
      id: randomUUID(),
      reference: 'Mateo 25:21',
      text: 'Sobre poco has sido fiel, sobre mucho te pondré; entra en el gozo de tu señor.',
      interpretation: 'La fidelidad en presupuestos pequeños valida tu madurez para dirigir proyectos empresariales mayores.',
      recommendedLevel: 1,
      topic: 'Finanzas',
    },
    {
      id: randomUUID(),
      reference: 'Eclesiastés 11:2',
      text: 'Reparte a siete, y aun a ocho; porque no sabes el mal que ha de venir sobre la tierra.',
      interpretation: 'Diversificación inteligente. Distribuir los riesgos comerciales protege tus fuentes de ingresos activas.',
      recommendedLevel: 3,
      topic: 'Finanzas',
    },
    {
      id: randomUUID(),
      reference: 'Proverbios 27:23',
      text: 'Sé diligente en conocer el estado de tus ovejas, y presta atención a tus rebaños.',
      interpretation: 'Monitorea tus métricas. Ignorar tus números de ingresos y egresos es el primer paso al caos administrativo.',
      recommendedLevel: 2,
      topic: 'Finanzas',
    },
    {
      id: randomUUID(),
      reference: 'Hechos 20:35',
      text: 'En todo os he enseñado que, trabajando así, se debe ayudar a los necesitados, y recordar las palabras: Más bienaventurado es dar que recibir.',
      interpretation: 'La máxima del reino. La acumulación no es el fin, el fin es la multiplicación generosa en otros.',
      recommendedLevel: 1,
      topic: 'Finanzas',
    },
    {
      id: randomUUID(),
      reference: 'Salmos 24:1',
      text: 'De Jehová es la tierra y su plenitud; el mundo, y los que en él habitan.',
      interpretation: 'Principio de mayordomía: eres un administrador temporal de sus recursos para expandir bienestar.',
      recommendedLevel: 1,
      topic: 'Finanzas',
    },

    // TÓPICO: DOMINIO PROPIO (30 Versículos)
    {
      id: randomUUID(),
      reference: 'Proverbios 25:28',
      text: 'Como ciudad derribada y sin muro es el hombre cuyo espíritu no tiene rienda suelta.',
      interpretation: 'El dominio propio es el muro de protección de tus hábitos. Sin templanza, cualquier distracción destruye tus metas.',
      recommendedLevel: 1,
      topic: 'Dominio Propio',
    },
    {
      id: randomUUID(),
      reference: 'Gálatas 5:22-23',
      text: 'Mas el fruto del Espíritu es... templanza; contra tales cosas no hay ley.',
      interpretation: 'La templanza no se fuerza con voluntad bruta, se cultiva rindiendo el día en oración desde la primera hora.',
      recommendedLevel: 1,
      topic: 'Dominio Propio',
    },
    {
      id: randomUUID(),
      reference: '2 Timoteo 1:7',
      text: 'Porque no nos ha dado Dios espíritu de cobardía, sino de poder, de amor y de dominio propio.',
      interpretation: 'La autoconfianza conductual es una herencia divina. Tienes la capacidad de gobernar tus impulsos hoy.',
      recommendedLevel: 1,
      topic: 'Dominio Propio',
    },
    {
      id: randomUUID(),
      reference: 'Proverbios 16:32',
      text: 'Mejor es el que tarda en airarse que el fuerte; y el que se enseñorea de su espíritu, que el que toma una ciudad.',
      interpretation: 'El autoliderazgo precede al liderazgo externo. Dominar tus reacciones te hace invulnerable ante el caos exterior.',
      recommendedLevel: 2,
      topic: 'Dominio Propio',
    },
    {
      id: randomUUID(),
      reference: '1 Corintios 9:25',
      text: 'Todo aquel que lucha, de todo se abstiene; ellos, a la verdad, para recibir una corona corruptible, pero nosotros, una incorruptible.',
      interpretation: 'Foco y renuncia. Para alcanzar la visión trimestral, debes decir "no" a decenas de opciones aparentemente buenas.',
      recommendedLevel: 2,
      topic: 'Dominio Propio',
    },
    {
      id: randomUUID(),
      reference: 'Proverbios 29:11',
      text: 'El necio da rienda suelta a toda su ira, mas el sabio al fin la sosiega.',
      interpretation: 'Pausa sagrada. Ante una provocación o estrés, detente 5 segundos antes de responder para mantener el control.',
      recommendedLevel: 1,
      topic: 'Dominio Propio',
    },
    {
      id: randomUUID(),
      reference: 'Proverbios 15:1',
      text: 'La blanda respuesta quita la ira; mas la palabra áspera hace subir el furor.',
      interpretation: 'Mayordomía relacional. Sostener la templanza al hablar protege la paz mental de tus colaboradores y familia.',
      recommendedLevel: 1,
      topic: 'Dominio Propio',
    },
    {
      id: randomUUID(),
      reference: '1 Pedro 4:7',
      text: 'Mas el fin de todas las cosas se acerca; sed, pues, sobrios, y velad en oración.',
      interpretation: 'Sobriedad cognitiva. Reduce el ruido y las notificaciones para orar y gobernar conscientemente tu día.',
      recommendedLevel: 2,
      topic: 'Dominio Propio',
    },
    {
      id: randomUUID(),
      reference: 'Tito 2:12',
      text: 'Enseñándonos que, renunciando a la impiedad... vivamos en este siglo sobria, justa y piadosamente.',
      interpretation: 'La sobriedad conductual te permite evaluar decisiones estratégicas sin distorsión de emociones transitorias.',
      recommendedLevel: 2,
      topic: 'Dominio Propio',
    },
    {
      id: randomUUID(),
      reference: 'Santiago 1:19',
      text: 'Por esto, mis amados hermanos, todo hombre sea pronto para oír, tardo para hablar, tardo para airarse.',
      interpretation: 'Escucha activa. Domina el impulso de responder de inmediato; dale espacio al otro para comunicarse.',
      recommendedLevel: 1,
      topic: 'Dominio Propio',
    },
    {
      id: randomUUID(),
      reference: 'Efesios 4:26',
      text: 'Airaos, pero no pequéis; no se ponga el sol sobre vuestro enojo.',
      interpretation: 'Procesamiento emocional diario. No te vayas a dormir albergando resentimiento; la revisión nocturna limpia tu mente.',
      recommendedLevel: 1,
      topic: 'Dominio Propio',
    },
    {
      id: randomUUID(),
      reference: 'Proverbios 4:23',
      text: 'Sobre toda cosa guardada, guarda tu corazón; porque de él mana la vida.',
      interpretation: 'Filtra lo que ingresa a tu mente. Protege la primera hora de tu mañana de las distracciones del mundo.',
      recommendedLevel: 1,
      topic: 'Dominio Propio',
    },
    {
      id: randomUUID(),
      reference: 'Mateo 26:41',
      text: 'Velad y orad, para que no entréis en tentación; el espíritu a la verdad está dispuesto, pero la carne es débil.',
      interpretation: 'Diseño de entorno. No confíes en tu fuerza de voluntad; elimina la tentación/fricción de tu campo de vista.',
      recommendedLevel: 1,
      topic: 'Dominio Propio',
    },
    {
      id: randomUUID(),
      reference: 'Romanos 12:1',
      text: '...que presentéis vuestros cuerpos en sacrificio vivo, santo, agradable a Dios, que es vuestro culto racional.',
      interpretation: 'Mayordomía física. Gobernar lo que comes y las horas que duermes es un acto espiritual de templanza.',
      recommendedLevel: 1,
      topic: 'Dominio Propio',
    },
    {
      id: randomUUID(),
      reference: '1 Tesalonicenses 5:6',
      text: 'Por tanto, no durmamos como los demás, sino velemos y seamos sobrios.',
      interpretation: 'Vigilancia diaria. No permitas que el cansancio te arrastre a conductas reactivas destructivas.',
      recommendedLevel: 2,
      topic: 'Dominio Propio',
    },
    {
      id: randomUUID(),
      reference: 'Colosenses 3:5',
      text: 'Haced morir, pues, lo terrenal en vosotros: fornicación, impureza, pasiones desordenadas...',
      interpretation: 'Identifica y remueve proactivamente los hábitos o conductas desordenadas que mitigan tu enfoque.',
      recommendedLevel: 2,
      topic: 'Dominio Propio',
    },
    {
      id: randomUUID(),
      reference: '1 Corintios 6:12',
      text: 'Todas las cosas me son lícitas, mas no todas convienen; todas las cosas me son lícitas, mas yo no me dejaré dominar de ninguna.',
      interpretation: 'Soberanía mental. Si una aplicación, juego o hábito te domina, desinstálalo de inmediato. Mantén tu libertad.',
      recommendedLevel: 3,
      topic: 'Dominio Propio',
    },
    {
      id: randomUUID(),
      reference: 'Proverbios 13:3',
      text: 'El que guarda su boca guarda su vida; mas el que mucho abre sus labios tendrá calamidad.',
      interpretation: 'Control en la comunicación. Evita prometer de más o hablar bajo la influencia del orgullo temporal.',
      recommendedLevel: 1,
      topic: 'Dominio Propio',
    },
    {
      id: randomUUID(),
      reference: 'Proverbios 21:23',
      text: 'El que guarda su boca y su lengua, su alma guarda de angustias.',
      interpretation: 'El silencio sabio previene crisis relacionales que sabotean tu paz y energía diaria.',
      recommendedLevel: 2,
      topic: 'Dominio Propio',
    },
    {
      id: randomUUID(),
      reference: 'Tito 1:8',
      text: 'Sino hospedador, amante de lo bueno, sobrio, justo, santo, dueño de sí mismo.',
      interpretation: 'Dueño de ti mismo. Tu identidad reside en la templanza, no en la impulsividad de tus deseos corporales.',
      recommendedLevel: 2,
      topic: 'Dominio Propio',
    },
    {
      id: randomUUID(),
      reference: '2 Pedro 1:5-6',
      text: '...añadid a vuestra fe virtud; a la virtud, conocimiento; al conocimiento, dominio propio; al dominio propio, paciencia...',
      interpretation: 'Eslabones de la madurez. El conocimiento sin dominio propio engendra soberbia; cultiva el autogobierno.',
      recommendedLevel: 2,
      topic: 'Dominio Propio',
    },
    {
      id: randomUUID(),
      reference: 'Proverbios 23:2',
      text: 'Y pon cuchillo a tu garganta, si tienes gran apetito.',
      interpretation: 'Frecuencia en límites. Si dectectas un desorden recurrente en tu vida, impone límites físicos infranqueables.',
      recommendedLevel: 1,
      topic: 'Dominio Propio',
    },
    {
      id: randomUUID(),
      reference: 'Lucas 9:23',
      text: 'Si alguno quiere venir en pos de mí, niéguese a sí mismo, tome su cruz cada día, y sígame.',
      interpretation: 'Disciplina diaria. El crecimiento espiritual requiere negación constante de la comodidad para abrazar el propósito.',
      recommendedLevel: 1,
      topic: 'Dominio Propio',
    },
    {
      id: randomUUID(),
      reference: 'Romanos 6:12',
      text: 'No reine, pues, el pecado en vuestro cuerpo de modo que lo obedezcáis en sus concupiscencias.',
      interpretation: 'Gobierna tus pensamientos antes de que se encarnen en hábitos automáticos destructivos.',
      recommendedLevel: 2,
      topic: 'Dominio Propio',
    },
    {
      id: randomUUID(),
      reference: 'Efesios 5:18',
      text: 'No os embriaguéis con vino, en lo cual hay disolución; antes bien sed llenos del Espíritu.',
      interpretation: 'La llenura espiritual expande tu discernimiento; el aturdimiento artificial destruye tus murallas de autodisciplina.',
      recommendedLevel: 2,
      topic: 'Dominio Propio',
    },
    {
      id: randomUUID(),
      reference: 'Colosenses 4:6',
      text: 'Sea vuestra palabra siempre con gracia, sazonada con sal, para que sepáis cómo debéis responder a cada uno.',
      interpretation: 'Templanza relacional. Respuestas meditadas y cargadas de respeto abren negociaciones complejas con éxito.',
      recommendedLevel: 1,
      topic: 'Dominio Propio',
    },
    {
      id: randomUUID(),
      reference: '1 Corintios 10:13',
      text: 'No os ha sobrevenido ninguna tentación que no sea humana; pero fiel es Dios, que no os dejará ser tentados más de lo que podéis resistir...',
      interpretation: 'Resistencia garantizada. No hay excusa de fatiga que justifique comprometer tu integridad el día de hoy.',
      recommendedLevel: 1,
      topic: 'Dominio Propio',
    },
    {
      id: randomUUID(),
      reference: 'Romanos 13:14',
      text: 'Sino vestíos del Señor Jesucristo, y no proveáis para los deseos de la carne.',
      interpretation: 'Huye del riesgo. Si eres propenso a una tentación de distracción, no crees las circunstancias propicias para caer.',
      recommendedLevel: 2,
      topic: 'Dominio Propio',
    },
    {
      id: randomUUID(),
      reference: '1 Pedro 1:13',
      text: 'Por tanto, ceñid los lomos de vuestro entendimiento, sed sobrios, y esperad por completo en la gracia...',
      interpretation: 'Ceñid el entendimiento. Mantén la claridad mental evitando alimentar pensamientos improductivos o de queja.',
      recommendedLevel: 2,
      topic: 'Dominio Propio',
    },
    {
      id: randomUUID(),
      reference: '1 Pedro 5:8',
      text: 'Sed sobrios, y velad; porque vuestro adversario el diablo, como león rugiente, anda alrededor buscando a quien devorar.',
      interpretation: 'Mantente alerta. El caos y la reactividad son trampas para sacarte del propósito diario. Vela y haz tu diario.',
      recommendedLevel: 1,
      topic: 'Dominio Propio',
    },

    // TÓPICO: CRECIMIENTO Y TRABAJO (30 Versículos)
    {
      id: randomUUID(),
      reference: 'Colosenses 3:23',
      text: 'Y todo lo que hagáis, hacedlo de corazón, como para el Señor y no para los hombres.',
      interpretation: 'Eleva el estándar de tu trabajo. La excelencia en lo oculto es lo que define tu nivel de impacto.',
      recommendedLevel: 2,
      topic: 'Crecimiento',
    },
    {
      id: randomUUID(),
      reference: 'Proverbios 12:1',
      text: 'El que ama la instrucción ama la sabiduría; mas el que aborrece la reprensión es ignorante.',
      interpretation: 'La autoeducación diaria no es opcional. Dedica tiempo a aprender algo que puedas aplicar de inmediato.',
      recommendedLevel: 2,
      topic: 'Crecimiento',
    },
    {
      id: randomUUID(),
      reference: 'Eclesiastés 9:10',
      text: 'Todo lo que te viniere a la mano para hacer, hazlo según tus fuerzas.',
      interpretation: 'El poder es la acción. Hazlo con la máxima energía disponible hoy, sin postergar lo prioritario.',
      recommendedLevel: 1,
      topic: 'Crecimiento',
    },
    {
      id: randomUUID(),
      reference: 'Proverbios 10:4',
      text: 'La mano negligente empobrece; mas la mano de los diligentes enriquece.',
      interpretation: 'La consistencia supera al talento. Tu diligencia diaria edifica riqueza y genera reputación sólida.',
      recommendedLevel: 1,
      topic: 'Crecimiento',
    },
    {
      id: randomUUID(),
      reference: 'Proverbios 13:4',
      text: 'El alma del perezoso desea, y nada alcanza; mas el alma de los diligentes será prosperada.',
      interpretation: 'Abandona los deseos vacíos de planificación teórica. Satisface tu alma con la ejecución diligente.',
      recommendedLevel: 1,
      topic: 'Crecimiento',
    },
    {
      id: randomUUID(),
      reference: 'Proverbios 14:23',
      text: 'En todo trabajo hay ganancia; mas las vanas palabras de los labios conducen a la penuria.',
      interpretation: 'Menos retórica y más ejecución. El avance real está en completar tareas de tu plan, no en solo hablar de ellas.',
      recommendedLevel: 1,
      topic: 'Crecimiento',
    },
    {
      id: randomUUID(),
      reference: 'Proverbios 22:29',
      text: '¿Has visto hombre solícito en su trabajo? Delante de los reyes estará; no estará delante de los de baja condición.',
      interpretation: 'Maestría técnica. La especialización y velocidad en tu labor profesional abren puertas de liderazgo inalcanzables.',
      recommendedLevel: 2,
      topic: 'Crecimiento',
    },
    {
      id: randomUUID(),
      reference: 'Proverbios 6:6-8',
      text: 'Ve a la hormiga, oh perezoso, mira sus caminos, y sé sabio; la cual no teniendo capitán... prepara en el verano su comida.',
      interpretation: 'Disciplina autogestionada. Trabaja con excelencia sin requerir que otros te supervisen de continuo.',
      recommendedLevel: 1,
      topic: 'Crecimiento',
    },
    {
      id: randomUUID(),
      reference: 'Filipenses 4:13',
      text: 'Todo lo puedo en Cristo que me fortalece.',
      interpretation: 'Tus recursos mentales y tu ingenio profesional provienen de la fortaleza espiritual diaria.',
      recommendedLevel: 1,
      topic: 'Crecimiento',
    },
    {
      id: randomUUID(),
      reference: 'Josué 1:9',
      text: 'Mira que te mando que te esfuerces y seas valiente; no temas ni desmayes, porque Jehová tu Dios estará contigo...',
      interpretation: 'Valentía conductual. Toma las decisiones incómodas que has postergado; el respaldo está garantizado.',
      recommendedLevel: 1,
      topic: 'Crecimiento',
    },
    {
      id: randomUUID(),
      reference: 'Romanos 12:11',
      text: 'En lo que requiere diligencia, no perezosos; fervientes en espíritu, sirviendo al Señor.',
      interpretation: 'La diligencia es una forma de adoración. Imprime pasión e integridad a tus entregas y proyectos hoy.',
      recommendedLevel: 2,
      topic: 'Crecimiento',
    },
    {
      id: randomUUID(),
      reference: 'Proverbios 12:24',
      text: 'La mano de los diligentes señoreará; mas la negligencia será tributaria.',
      interpretation: 'El autogobierno conductual te posiciona para liderar y dirigir organizaciones. La pasividad te hace dependiente.',
      recommendedLevel: 2,
      topic: 'Crecimiento',
    },
    {
      id: randomUUID(),
      reference: 'Gálatas 6:9',
      text: 'No nos cansemos, pues, de hacer bien; porque a su tiempo segaremos, si no desmayamos.',
      interpretation: 'Persistencia resiliente. El fruto verdadero de tus objetivos SMART toma tiempo; continúa sembrando con amor.',
      recommendedLevel: 1,
      topic: 'Crecimiento',
    },
    {
      id: randomUUID(),
      reference: 'Hebreos 6:12',
      text: '...a fin de que no os hagáis perezosos, sino imitadores de aquellos que por la fe y la paciencia heredan las promesas.',
      interpretation: 'La combinación de fe y paciencia es el motor que desbloquea las metas de tu planeamiento trimestral.',
      recommendedLevel: 2,
      topic: 'Crecimiento',
    },
    {
      id: randomUUID(),
      reference: '2 Tesalonicenses 3:10',
      text: 'Porque también cuando estábamos con vosotros, os mandábamos esto: Si alguno no quiere trabajar, tampoco coma.',
      interpretation: 'Responsabilidad biológica y espiritual. El trabajo enfocado dignifica y sostiene el desarrollo del hogar.',
      recommendedLevel: 1,
      topic: 'Crecimiento',
    },
    {
      id: randomUUID(),
      reference: 'Santiago 1:22',
      text: 'Pero sed hacedores de la palabra, y no tan solamente oidores, engañándoos a vosotros mismos.',
      interpretation: 'La autoeducación debe encarnarse. Cada lección debe traducirse en una acción en menos de 5 minutos.',
      recommendedLevel: 1,
      topic: 'Crecimiento',
    },
    {
      id: randomUUID(),
      reference: 'Proverbios 19:15',
      text: 'La pereza hace caer en profundo sueño, y el alma negligente padecerá hambre.',
      interpretation: 'Vence el letargo. La procrastinación destruye tus niveles de energía diarios; muévete hacia la acción.',
      recommendedLevel: 1,
      topic: 'Crecimiento',
    },
    {
      id: randomUUID(),
      reference: '1 Corintios 15:58',
      text: 'Así que, hermanos míos amados, estad firmes y constantes, creciendo en la obra del Señor siempre...',
      interpretation: 'Constancia inquebrantable. Tu constancia define la profundidad del legado que estás edificando hoy.',
      recommendedLevel: 2,
      topic: 'Crecimiento',
    },
    {
      id: randomUUID(),
      reference: 'Colosenses 3:17',
      text: 'Y todo lo que hagáis, sea de palabra o de hecho, hacedlo todo en el nombre del Señor Jesús...',
      interpretation: 'Alineación identitaria. Cada correo electrónico, llamada o reporte lleva tu sello de integridad espiritual.',
      recommendedLevel: 1,
      topic: 'Crecimiento',
    },
    {
      id: randomUUID(),
      reference: '2 Pedro 3:18',
      text: 'Antes bien, creced en la gracia y el conocimiento de nuestro Señor y Salvador Jesucristo.',
      interpretation: 'Mejora continua. La estandarización de hábitos te da el espacio para crecer en gracia y sabiduría.',
      recommendedLevel: 2,
      topic: 'Crecimiento',
    },
    {
      id: randomUUID(),
      reference: 'Efesios 5:15-16',
      text: 'Mirad, pues, con diligencia cómo andéis, no como necios sino como sabios, aprovechando bien el tiempo...',
      interpretation: 'Mayordomía del tiempo. Planifica tu agenda mañana hoy para evitar caer en las urgencias de otros.',
      recommendedLevel: 2,
      topic: 'Crecimiento',
    },
    {
      id: randomUUID(),
      reference: 'Salmos 90:12',
      text: 'Enséñanos de tal modo a contar nuestros días, que traigamos al corazón sabiduría.',
      interpretation: 'Contar los días. La racha y la revisión diaria son recordatorios de la finitud de nuestro tiempo para edificar.',
      recommendedLevel: 1,
      topic: 'Crecimiento',
    },
    {
      id: randomUUID(),
      reference: 'Salmos 1:1-3',
      text: 'Bienaventurado el varón que... en la ley de Jehová está su delicia... Será como árbol plantado junto a corrientes...',
      interpretation: 'Estabilidad de raíces. El devocional diario nutre tus raíces para prosperar incluso en estaciones de sequía comercial.',
      recommendedLevel: 1,
      topic: 'Crecimiento',
    },
    {
      id: randomUUID(),
      reference: 'Proverbios 4:7',
      text: 'Sabiduría ante todo; adquiere sabiduría; y sobre todas tus posesiones adquiere inteligencia.',
      interpretation: 'Invierte en discernimiento. Antes de adquirir activos físicos, adquiere conocimiento para administrarlos bien.',
      recommendedLevel: 2,
      topic: 'Crecimiento',
    },
    {
      id: randomUUID(),
      reference: 'Lucas 2:52',
      text: 'Y Jesús crecía en sabiduría y en estatura, y en gracia para con Dios y los hombres.',
      interpretation: 'Crecimiento integral de 4 pilares: sabiduría (mente), estatura (cuerpo), gracia con Dios (fe) y hombres (relaciones).',
      recommendedLevel: 1,
      topic: 'Crecimiento',
    },
    {
      id: randomUUID(),
      reference: 'Filipenses 3:13-14',
      text: '...olvidando ciertamente lo que queda atrás, y extendiéndome a lo que está delante, prosigo a la meta...',
      interpretation: 'Reseteo diario. Las fallas de ayer se limpian en la revisión. Hoy es un nuevo lienzo para avanzar.',
      recommendedLevel: 2,
      topic: 'Crecimiento',
    },
    {
      id: randomUUID(),
      reference: '1 Timoteo 4:15',
      text: 'Medita en estas cosas; ocúpate en ellas, para que tu aprovechamiento sea manifiesto a todos.',
      interpretation: 'Ocupación profunda. Bloquea tiempo libre de interrupciones para el trabajo profundo que mueve tu negocio.',
      recommendedLevel: 2,
      topic: 'Crecimiento',
    },
    {
      id: randomUUID(),
      reference: 'Lucas 16:10',
      text: 'El que es fiel en lo muy poco, también en lo más es fiel; y el que en lo muy poco es injusto, también en lo más es injusto.',
      interpretation: 'La micro-ejecución diaria. Si dominas las micro-victorias, gobernarás proyectos de gran escala con integridad.',
      recommendedLevel: 1,
      topic: 'Crecimiento',
    },
    {
      id: randomUUID(),
      reference: 'Proverbios 19:2',
      text: 'El alma sin ciencia no es buena, y el que se apresura con los pies, peca.',
      interpretation: 'Ejecución medida. Estudiar tus métricas del negocio te previene de cometer errores apresurados de inversión.',
      recommendedLevel: 2,
      topic: 'Crecimiento',
    },
    {
      id: randomUUID(),
      reference: 'Mateo 25:29',
      text: 'Porque al que tiene, le será dado, y tendrá más; y al que no tiene, aun lo que tiene le será quitado.',
      interpretation: 'Principio de productividad: el uso activo de tus capacidades genera multiplicación; la pasividad causa atrofia.',
      recommendedLevel: 2,
      topic: 'Crecimiento',
    },

    // TÓPICO: IDENTIDAD Y AUTOCONFIANZA (30 Versículos)
    {
      id: randomUUID(),
      reference: 'Jeremías 31:3',
      text: 'Con amor eterno te he amado; por tanto, te prolongué mi misericordia.',
      interpretation: 'Tu valor identitario como ser humano no depende de tu nivel de productividad diaria, sino del amor de tu creador.',
      recommendedLevel: 1,
      topic: 'Identidad',
    },
    {
      id: randomUUID(),
      reference: 'Romanos 12:2',
      text: 'No se amolden a este siglo, sino transfórmense mediante la renovación de su mente...',
      interpretation: 'La renovación mental y la alineación identitaria diaria precede a toda transformación conductual sostenible.',
      recommendedLevel: 1,
      topic: 'Identidad',
    },
    {
      id: randomUUID(),
      reference: 'Génesis 1:27',
      text: 'Y creó Dios al hombre a su imagen, a imagen de Dios lo creó; varón y hembra los creó.',
      interpretation: 'Diseño original. Tu estructura interna está pensada para la excelencia, el orden y la creatividad transformadora.',
      recommendedLevel: 1,
      topic: 'Identidad',
    },
    {
      id: randomUUID(),
      reference: 'Salmos 139:14',
      text: 'Te alabaré; porque formidables, maravillosas son tus obras; estoy maravillado, y mi alma lo sabe muy bien.',
      interpretation: 'Autoconfianza identitaria. Reconocer tu diseño formidable mitiga de inmediato el síndrome del impostor.',
      recommendedLevel: 1,
      topic: 'Identidad',
    },
    {
      id: randomUUID(),
      reference: 'Efesios 2:10',
      text: 'Porque somos hechura suya, creados en Cristo Jesús para buenas obras, las cuales Dios preparó de antemano para que anduviésemos en ellas.',
      interpretation: 'Camino trazado. Tus objetivos del trimestre deben reflejar las buenas obras que fuiste diseñado para liderar hoy.',
      recommendedLevel: 2,
      topic: 'Identidad',
    },
    {
      id: randomUUID(),
      reference: '1 Pedro 2:9',
      text: 'Mas vosotros sois linaje escogido, real sacerdocio, nación santa, pueblo adquirido por Dios...',
      interpretation: 'Identidad de Reino. No operes desde la mentalidad de esclavo o víctima; lidera desde tu identidad.',
      recommendedLevel: 2,
      topic: 'Identidad',
    },
    {
      id: randomUUID(),
      reference: '2 Corintios 5:17',
      text: 'De modo que si alguno está en Cristo, nueva criatura es; las cosas viejas pasaron; he aquí todas son hechas nuevas.',
      interpretation: 'Reinicio absoluto. Tu historial anterior de malos hábitos o fracaso comercial no limita lo que puedes construir hoy.',
      recommendedLevel: 1,
      topic: 'Identidad',
    },
    {
      id: randomUUID(),
      reference: 'Juan 1:12',
      text: 'Mas a todos los que le recibieron, a los que creen en su nombre, les dio potestad de ser hechos hijos de Dios.',
      interpretation: 'Filiación divina. Tu herencia de autoridad espiritual y autogobierno se sustenta en tu estatus de hijo amado.',
      recommendedLevel: 1,
      topic: 'Identidad',
    },
    {
      id: randomUUID(),
      reference: 'Gálatas 2:20',
      text: 'Con Cristo estoy juntamente crucificado, y ya no vivo yo, mas vive Cristo en mí; y lo que ahora vivo en la carne, lo vivo en la fe...',
      interpretation: 'La esencia que precede a la acción. No se trata de "hacer más" para ser válido, sino de actuar desde quien ya eres.',
      recommendedLevel: 2,
      topic: 'Identidad',
    },
    {
      id: randomUUID(),
      reference: 'Colosenses 3:3',
      text: 'Porque habéis muerto, y vuestra vida está escondida con Cristo en Dios.',
      interpretation: 'Protección absoluta. Tu paz interior no puede verse afectada por las variaciones del mercado o la opinión ajena.',
      recommendedLevel: 2,
      topic: 'Identidad',
    },
    {
      id: randomUUID(),
      reference: 'Romanos 8:37',
      text: 'Antes, en todas estas cosas somos más que vencedores por medio de aquel que nos amó.',
      interpretation: 'Mentalidad de victoria. Los desafíos comerciales del día de hoy ya están resueltos en tu identidad en Él.',
      recommendedLevel: 1,
      topic: 'Identidad',
    },
    {
      id: randomUUID(),
      reference: 'Efesios 1:4',
      text: '...según nos escogió en él antes de la fundación del mundo, para que fuésemos santos y sin mancha delante de él...',
      interpretation: 'Escogido con propósito. Fuiste diseñado con una asignación específica antes de que el caos del mundo te rodeara.',
      recommendedLevel: 2,
      topic: 'Identidad',
    },
    {
      id: randomUUID(),
      reference: 'Juan 15:15',
      text: 'Ya no os llamaré siervos, porque el siervo no sabe lo que hace su señor; pero os he llamado amigos...',
      interpretation: 'Relación íntima. La intimidad con Dios elimina el temor a fallar y asienta tu capacidad de discernimiento hoy.',
      recommendedLevel: 1,
      topic: 'Identidad',
    },
    {
      id: randomUUID(),
      reference: 'Romanos 8:1',
      text: 'Ahora, pues, ninguna condenación hay para los que están en Cristo Jesús, los que no andan conforme a la carne...',
      interpretation: 'Libre de culpa. Si fallas un día en tu racha, no te sumerjas en la culpa. Haz tu diario hoy y sigue adelante.',
      recommendedLevel: 1,
      topic: 'Identidad',
    },
    {
      id: randomUUID(),
      reference: 'Romanos 8:17',
      text: 'Y si hijos, también herederos; herederos de Dios y coherederos con Cristo, si es que padecemos juntamente con él...',
      interpretation: 'Herencia de propósito. Todo lo que administras es un recurso prestado para manifestar la gloria de Dios en tu oikos.',
      recommendedLevel: 2,
      topic: 'Identidad',
    },
    {
      id: randomUUID(),
      reference: '1 Juan 3:1',
      text: 'Mirad cuál amor nos ha dado el Padre, para que seamos llamados hijos de Dios; por esto el mundo no nos conoce...',
      interpretation: 'Identidad blindada. No busques la validación de la cultura corporativa fría; reposa en tu valor intrínseco.',
      recommendedLevel: 1,
      topic: 'Identidad',
    },
    {
      id: randomUUID(),
      reference: 'Colosenses 2:10',
      text: '...y vosotros estáis completos en él, que es la cabeza de todo principado y potestad.',
      interpretation: 'Estatus completo. No necesitas añadirle logros estresantes a tu vida para sentirte completo. Actúa desde la plenitud.',
      recommendedLevel: 2,
      topic: 'Identidad',
    },
    {
      id: randomUUID(),
      reference: 'Filipenses 3:20',
      text: 'Mas nuestra ciudadanía está en los cielos, de donde también esperamos al Salvador, al Señor Jesucristo.',
      interpretation: 'Mentalidad celestial. Tus estándares éticos de negocio se rigen por las leyes del cielo, no por la astucia del mundo.',
      recommendedLevel: 2,
      topic: 'Identidad',
    },
    {
      id: randomUUID(),
      reference: '2 Corintios 5:21',
      text: 'Al que no conoció pecado, por nosotros lo hizo pecado, para que nosotros fueseis hechos justicia de Dios en él.',
      interpretation: 'Justicia posicional. Sostén tu frente en alto; eres depositario de la justicia y la dignidad de tu creador.',
      recommendedLevel: 2,
      topic: 'Identidad',
    },
    {
      id: randomUUID(),
      reference: 'Isaías 43:1',
      text: 'No temas, porque yo te redimí; te puse nombre, mío eres tú.',
      interpretation: 'Pertenencia absoluta. La tormentas de la economía o los desafíos familiares no alteran tu destino eterno.',
      recommendedLevel: 1,
      topic: 'Identidad',
    },
    {
      id: randomUUID(),
      reference: 'Sofonías 3:17',
      text: 'Jehová está en medio de ti, poderoso, él salvará; se gozará sobre ti con alegría, callará de amor...',
      interpretation: 'Amor deleitoso. Tu creador celebra tus pequeños pasos diarios de constancia con regocijo absoluto.',
      recommendedLevel: 1,
      topic: 'Identidad',
    },
    {
      id: randomUUID(),
      reference: 'Mateo 5:14',
      text: 'Vosotros sois la luz del mundo; una ciudad asentada sobre un monte no se puede esconder.',
      interpretation: 'Influencia ineludible. Tus hábitos, honestidad comercial e integridad familiar son una luz en un mercado hostil.',
      recommendedLevel: 1,
      topic: 'Identidad',
    },
    {
      id: randomUUID(),
      reference: 'Efesios 5:8',
      text: 'Porque en otro tiempo erais tinieblas, mas ahora sois luz en el Señor; andad como hijos de luz.',
      interpretation: 'Coherencia identitaria. Que tus decisiones de hoy reflejen la luz de tu nueva identidad.',
      recommendedLevel: 1,
      topic: 'Identidad',
    },
    {
      id: randomUUID(),
      reference: '1 Juan 4:4',
      text: 'Hijitos, vosotros sois de Dios, y los habéis vencido; porque mayor es el que está en vosotros, que el que está en el mundo.',
      interpretation: 'Mayor fortaleza. Las barreras complejas de tu emprendimiento se superan operando desde la unción de tu identidad.',
      recommendedLevel: 1,
      topic: 'Identidad',
    },
    {
      id: randomUUID(),
      reference: 'Juan 8:32',
      text: '...y conoceréis la verdad, y la verdad os hará libres.',
      interpretation: 'Libertad cognitiva. Rompe las mentiras de incapacidad que el sistema intenta inyectarte a diario.',
      recommendedLevel: 1,
      topic: 'Identidad',
    },
    {
      id: randomUUID(),
      reference: 'Romanos 8:31',
      text: '¿Qué, pues, diremos a esto? Si Dios es por nosotros, ¿quién contra nosotros?',
      interpretation: 'Respaldo absoluto. Sal al mercado con audacia santa hoy; estás respaldado por el diseñador de la creación.',
      recommendedLevel: 1,
      topic: 'Identidad',
    },
    {
      id: randomUUID(),
      reference: 'Gálatas 4:7',
      text: 'Así que ya no eres esclavo, sino hijo; y si hijo, también heredero de Dios por medio de Cristo.',
      interpretation: 'Libertad de herencia. Abandona el temor al fracaso financiero; tu Padre administra la provisión eterna.',
      recommendedLevel: 2,
      topic: 'Identidad',
    },
    {
      id: randomUUID(),
      reference: '1 Corintios 6:19-20',
      text: '¿O ignoráis que vuestro cuerpo es templo del Espíritu Santo... y que no sois vuestros? Porque habéis sido comprados por precio...',
      interpretation: 'Mayordomía del templo. Tratar tu cuerpo físico con cuidado y templanza es custodiar el templo del Espíritu.',
      recommendedLevel: 2,
      topic: 'Identidad',
    },
    {
      id: randomUUID(),
      reference: 'Deuteronomio 28:13',
      text: 'Te pondrá Jehová por cabeza, y no por cola; y estarás encima solamente, y no estarás debajo...',
      interpretation: 'Liderazgo posicional. Estás llamado a influenciar y transformar tu entorno comercial, no a ser moldeado por él.',
      recommendedLevel: 2,
      topic: 'Identidad',
    },
    {
      id: randomUUID(),
      reference: 'Apocalipsis 1:6',
      text: '...y nos hizo reyes y sacerdotes para Dios, su Padre; a él sea gloria e imperio por los siglos de los siglos.',
      interpretation: 'Identidad gubernamental. Tu llamado es gobernar con justicia tu negocio y oficiar con amor en tu sacerdocio familiar.',
      recommendedLevel: 3,
      topic: 'Identidad',
    }
  ];

  // Inserción Masiva Única (Bulk Insert)
  await db.insert(bibleVerses).values(verses);
  console.log(`Librería cargada con éxito con ${verses.length} versículos de alto rendimiento.`);

  const demoUserId = 'demo-user-id';
  
  try {
    await db.insert(users).values({
      id: demoUserId,
      name: 'Joel Pacheco',
      email: 'joel@journalingintegral.demo',
      password: 'demo-password-hash', // Contraseña para bypass local de administrador
      currentLevel: 1,
      streakCurrent: 5,
      streakMax: 12,
      lastEntryDate: new Date().toISOString().split('T')[0],
      createdAt: new Date().toISOString(),
    });
    console.log('Usuario demo inicializado.');
  } catch (e) {
    console.log('El usuario demo ya existe.');
  }

  const demoHabits = [
    {
      id: randomUUID(),
      userId: demoUserId,
      name: 'Orar 3 minutos al despertar',
      type: 'ESTANDARIZAR',
      strategyDetails: 'Dejar el teléfono móvil fuera de la habitación la noche anterior.',
      isActive: 1,
      createdAt: new Date().toISOString(),
    },
    {
      id: randomUUID(),
      userId: demoUserId,
      name: 'No revisar el celular la primera hora del día',
      type: 'OPTIMIZAR',
      strategyDetails: 'Usar un despertador analógico para evitar mirar notificaciones.',
      isActive: 1,
      createdAt: new Date().toISOString(),
    },
  ];

  for (const habit of demoHabits) {
    await db.insert(habits).values(habit);
  }
  console.log('Hábitos de ejemplo creados para el usuario demo.');

  await db.insert(quarterlyPlans).values({
    id: randomUUID(),
    userId: demoUserId,
    quarterLabel: 'Q1/2026',
    year: 2026,
    isActive: 1,
    fiveYearSpiritual: 'Ser un referente espiritual y mentor que guíe a otros a vivir una fe práctica con integridad profunda.',
    fiveYearBeing: 'Ser una persona físicamente sana, estable y con madurez emocional para liderar con generosidad.',
    fiveYearBusiness: 'Construir un negocio estable que opere bajo principios éticos y proporcione libertad de tiempo y recursos.',
    fiveYearRelations: 'Mantener un matrimonio ejemplar y formar un círculo íntimo de mentoría y comunidad sólida.',
    
    quarterlySpiritual: 'Consolidar el hábito del devocional diario sin interrupción tecnológica.',
    quarterlyBeing: 'Alcanzar una rutina de descanso regular que reduzca el cansancio residual acumulado.',
    quarterlyBusiness: 'Lanzar el producto mínimo viable de mi servicio de consultoría con 3 clientes validados.',
    quarterlyRelations: 'Tener una cena semanal de enfoque exclusivo con mi cónyuge sin distractores digitales.',

    smartObjectivesJson: JSON.stringify([
      { id: 'obj-1', objective: 'Registrar 20 días de journaling en los próximos 30 días.', targetDate: '2026-02-15', isCompleted: false },
      { id: 'obj-2', objective: 'Completar 1 hora de autoeducación enfocada en negocios cada semana.', targetDate: '2026-03-31', isCompleted: false }
    ]),
    
    actionsPlanJson: JSON.stringify([
      {
        metaIndex: 1,
        metaTitle: 'Estabilidad de Hábitos',
        actions: [
          { action: 'Hacer el diario de mañana por 5 minutos', frequency: 'Diaria', indicator: 'Check en la app' },
          { action: 'Chequeo de energía nocturno', frequency: 'Diaria', indicator: 'Registro en el sistema' }
        ]
      }
    ]),
    createdAt: new Date().toISOString(),
  });

  console.log('Planeamiento trimestral de demostración cargado exitosamente.');
  console.log('Inicialización completada.');
}

seed().catch((err) => {
  console.error('Error durante la inserción de datos semilla:', err);
  process.exit(1);
});